Test new bump style

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -27,14 +27,46 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Bump stable tag version
-        id: bump_stable
+      - name: Get current version tag
+        id: get_version
         uses: mathieudutour/github-tag-action@v6.2
         with:
           github_token:        ${{ secrets.GITHUB_TOKEN }}
           tag_prefix:          v
           default_bump:        {{ github.event.inputs.bump_level }}
-          release_branches: main
+          default_prerelease_bump: false
+          append_to_pre_release_tag: pre
+          pre_release_branches: main
+
+      - name: Resolve version
+        id: resolve_version
+        run: |
+          PREV_TAG="${{ steps.get_version.outputs.previous_tag }}"
+          STABLE_VERSION=""
+
+          if [[ "${{ github.ref }}" == refs/tags/v*.*.* ]]; then
+            STABLE_VERSION="${GITHUB_REF#refs/tags/v}"
+            echo "Triggered by tag push. Using version: $RESOLVED_VALUE"
+
+          elif [[ -n "$PREV_TAG" ]]; then
+            STABLE_VERSION="${PREV_TAG%-pre.*}"
+            echo "Not triggered by tag. Stripped pre-release from '$PREVIOUS_TAG' to get base version: $RESOLVED_VALUE"
+
+          else
+            echo "::error::Cannot resolve version" && exit 1
+          fi
+
+          echo "version=$STABLE_VERSION" >> "$GITHUB_OUTPUT"
+
+      - name: Create stable git tag
+        id: create_stable_tag
+        uses: mathieudutour/github-tag-action@v6.2
+        with:
+          github_token:        ${{ secrets.GITHUB_TOKEN }}
+          custom_tag:          ${{ steps.resolve_version.outputs.version }}
+          default_bump:        false
+          default_prerelease_bump: false
+          tag_prefix:          ''
 
       - name: Set up Python
         uses: actions/setup-python@v4
@@ -75,7 +107,7 @@ jobs:
       - name: Bump next prerelease tag
         uses: mathieudutour/github-tag-action@v6.2
         with:
-          release_branches:    '_NONE_'
+          release_branches:    '_NONE_'            # no branch generates stable tags here
           github_token:        ${{ secrets.GITHUB_TOKEN }}
           tag_prefix:          v
           default_bump:        patch
